-- ============================================
-- Migration 011: Chapa payments + manual proof fallback
-- Run once against an existing database, in order after migration_010.
-- ============================================

-- One row per Chapa checkout attempt. tx_ref is generated by us (unique)
-- and is how we look up "which invoice was this for" when Chapa redirects
-- the patient back or we verify the transaction server-side. A patient
-- retrying a failed payment creates a new row rather than reusing one, so
-- there's a full attempt history per invoice.
CREATE TABLE chapa_transactions (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
    patient_id INTEGER REFERENCES patients(id) ON DELETE CASCADE,
    tx_ref VARCHAR(100) UNIQUE NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending' | 'success' | 'failed'
    created_at TIMESTAMP DEFAULT NOW(),
    verified_at TIMESTAMP
);

-- Fallback for when a Chapa checkout gets interrupted (closed tab, network
-- drop, etc.) — the patient submits the transaction number their bank/Chapa
-- gave them plus a screenshot, and admin/receptionist reviews it manually.
-- The UNIQUE constraint on transaction_ref is the actual fraud guard: once
-- a reference has been submitted, it can never be submitted again, even by
-- a different patient — enforced at the database level, not just in code,
-- so it can't be bypassed by two requests racing each other.
CREATE TABLE payment_proofs (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
    patient_id INTEGER REFERENCES patients(id) ON DELETE CASCADE,
    transaction_ref VARCHAR(100) UNIQUE NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
    submitted_at TIMESTAMP DEFAULT NOW(),
    reviewed_by INTEGER REFERENCES users(id),
    reviewed_at TIMESTAMP,
    review_note VARCHAR(255)
);
